# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
logPL_C <- function(X, indset, cen, beta) {
    .Call('_glidars_logPL_C', PACKAGE = 'glidars', X, indset, cen, beta)
}

#'@export
val_pen <- function(Apo, w, nb, m, beta) {
    .Call('_glidars_val_pen', PACKAGE = 'glidars', Apo, w, nb, m, beta)
}

#'@export
roundvec <- function(beta, eps) {
    .Call('_glidars_roundvec', PACKAGE = 'glidars', beta, eps)
}

lasso_tree_single <- function(X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace, fullA = FALSE) {
    .Call('_glidars_lasso_tree_single', PACKAGE = 'glidars', X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace, fullA)
}

lasso_tree_multi <- function(X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace) {
    .Call('_glidars_lasso_tree_multi', PACKAGE = 'glidars', X, indset, Apo, nb, m, cen, lambda, w, inibeta, maxiter, eps, trace)
}

